package model;

public enum MessageType {
	INVALID_ADDRESS, //1
	INVALID_PORT,	//2
	PROBLEM_DISCONNECTING, //3
	INVALID_COORDINATES, //4
	SOCKET_FAILURE, //5
	INVALID_INPUT, //6
	INVALID_STRATEGY, //7
	STREAM_FAILURE, //8
	WRITING_FAILURE, //9
	RETURN_START, //10
	SERVER_LISTENING, //11
	PROTOCOL_IRREGULARITIES, //12
	SERVER_ILLEGAL_MOVE, //13
	SOCKET_CREATED; //1
}
